# Generated by Django 5.1.3 on 2024-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
