# Generated by Django 5.1.3 on 2024-12-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_retail',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_wholesale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(max_length=100),
        ),
    ]
