# Generated by Django 5.1.3 on 2024-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_distributor_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
